{{- if and (.Values.auth.enabled) (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
  {{- toYaml .Values.mailhog.labels | nindent 4 }}
  name: {{ .Values.mailhog.authFileSecret }}
  namespace: {{ .Values.mailhog_namespace }}
type: Opaque
data:
  {{ .Values.auth.fileName }}: {{ .Values.auth.fileContents | b64enc }}
{{- end -}}

