{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
  {{- toYaml .Values.mailhog.labels | nindent 4 }}
  namespace: {{ .Values.mailhog_namespace }}
imagePullSecrets:
{{- toYaml .Values.serviceAccount.imagePullSecrets | nindent 4 }}
{{- end }}
