apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  ports:
    - name: http
      port:  {{ .Values.configmap.PORT }}
      protocol: TCP
      targetPort:  {{ .Values.configmap.PORT }}
  selector:
    app: {{ .Chart.Name }}