{{- if and (.Values.outgoingSMTP.enabled) (not .Values.outgoingSMTP.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
  {{- toYaml .Values.mailhog.labels | nindent 4 }}
  name: {{ .Values.mailhog.outgoingSMTPSecret }}
  namespace: {{ .Values.mailhog_namespace }}
type: Opaque
data:
  {{ .Values.outgoingSMTP.fileName }}: {{ .Values.outgoingSMTP.fileContents | toJson | b64enc }}
{{- end -}}
