# All of the following are populated by Harness during deployment. These are
# temporary measures until IACv2 implements pod identities.
# https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html
environment:
 awsAccountId: "<+serviceVariables.awsAccountId>"
 name: "<+env.name>"
 oidcProvider: "<+serviceVariables.oidcProvider>"
 region: "<+pipeline.variables.region>"
 envState: "<+stage.variables.EnvState>"

metadata:
  labels:
    app: mailhog-coaching
  namespace: coaching
  annotations:
    repo: "https://github.com/Pluma-Health/mailhog-coaching"
    squad: "Pluma-Health"
    jiraKey: "PLUMA"

replica_count: 1

strategy:
  max_surge: 1
  max_unavailable: 1

container:
  image_pull_policy: IfNotPresent
  image:
    repository: 510467250861.dkr.ecr.us-east-1.amazonaws.com
    tag: <+stage.variables.Dockertag>

resources:
  cpu:
    limit: 500m
    request: 150m
  memory:
    limit: 512Mi
    request: 128Mi


configmap:
  enabled: true
  PORT: '8080'
  HOST: '0.0.0.0'
  env: 'production'

readinessProbe:
  httpGet:
    path: '/public/health/v1/ping'
    port: 8080
livenessProbe:
  port: 8080
  initialDelaySeconds: 5
  timeoutSeconds: 1



peerauthentication:
  enabled: true

verticalpodautoscaler:
  enabled: true

virtualservice_internal:
  enabled: false



  